spring:
  application:
    name: gradle-shard-module-sample

  # データソース設定
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Flyway設定
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: false  # Gradle Flywayプラグインとの競合回避
    clean-disabled: true

  # jOOQ設定
  jooq:
    sql-dialect: MYSQL
    
  # 国際化設定（MessageConfigで設定）
  
  # DevTools設定
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin,src/main/resources
    livereload:
      enabled: true

# ログ設定
logging:
  level:
    org.flywaydb: INFO
    org.jooq: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

# アプリケーション設定
app:
  demo-controller:
    enabled: true  # デモ用コントローラーを有効化

---
# 開発環境用設定
spring:
  config:
    activate:
      on-profile: dev
  
  flyway:
    # 開発環境ではシードデータも含める
    locations:
      - classpath:db/migration
      - classpath:db/seed
    clean-disabled: false

---
# テスト環境用設定
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:mysql://localhost:3306/mydb_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
  
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed
    clean-on-validation-error: true

---
# 本番環境用設定  
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  flyway:
    locations:
      - classpath:db/migration
    clean-disabled: true
    validate-on-migrate: true