spring:
  application:
    name: gradle-shard-module-sample

  # データソース設定
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # jOOQ設定
  jooq:
    sql-dialect: MYSQL
  
  # Flyway設定
  flyway:
    validate-on-migrate: false
    baseline-on-migrate: true
    
  # 国際化設定（MessageConfigで設定）
  
  # DevTools設定
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/kotlin,src/main/resources
    livereload:
      enabled: true

# ログ設定
logging:
  level:
    org.jooq: DEBUG

# アプリケーション設定
app:
  demo-controller:
    enabled: true  # デモ用コントローラーを有効化

# Actuator設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env,metrics,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Springdoc OpenAPI設定
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

---
# 開発環境用設定
spring:
  config:
    activate:
      on-profile: dev

---
# テスト環境用設定
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:mysql://localhost:3306/mydb_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8

---
# 本番環境用設定  
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}