name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:8.4.5
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -prootpassword"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client-8.0

    - name: Wait for MySQL and create user
      run: |
        echo "Waiting for MySQL service to be ready..."
        for i in {1..30}; do
          if mysqladmin ping -h"127.0.0.1" -P"3306" -u"root" -p"rootpassword" --silent; then
            echo "MySQL is ready!"
            break
          else
            echo "Attempt $i/30: MySQL not ready yet, waiting 5 seconds..."
            sleep 5
          fi
        done
        
        # Create database user
        echo "Creating database user..."
        mysql -h"127.0.0.1" -P"3306" -u"root" -p"rootpassword" -e "
          CREATE USER IF NOT EXISTS 'dbuser'@'%' IDENTIFIED BY 'dbpassword';
          GRANT ALL PRIVILEGES ON mydb.* TO 'dbuser'@'%';
          FLUSH PRIVILEGES;
        "
        
        # Verify user connection
        echo "Testing user connection..."
        mysqladmin ping -h"127.0.0.1" -P"3306" -u"dbuser" -p"dbpassword" --silent || {
          echo "ERROR: Could not connect to MySQL with dbuser"
          exit 1
        }
        echo "MySQL and user setup complete!"

    - name: Download Flyway CLI
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.10.0/flyway-commandline-10.10.0-linux-x64.tar.gz | tar xvz
        sudo cp flyway-10.10.0/flyway /usr/local/bin/
        sudo chmod +x /usr/local/bin/flyway

    - name: Download MySQL Connector
      run: |
        wget -O mysql-connector.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar

    - name: Run Flyway migration with CLI
      run: |
        flyway \
          -url=jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC \
          -user=dbuser \
          -password=dbpassword \
          -schemas=mydb \
          -locations=filesystem:persistence-module/src/main/resources/db/migration \
          -classpath=mysql-connector.jar \
          migrate
      env:
        FLYWAY_URL: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        FLYWAY_USER: dbuser
        FLYWAY_PASSWORD: dbpassword

    - name: Build persistence module (skip Flyway)
      run: ./gradlew :persistence-module:build -x flywayMigrate
      env:
        ORG_GRADLE_PROJECT_db_url: jdbc:mysql://127.0.0.1:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        ORG_GRADLE_PROJECT_db_user: dbuser
        ORG_GRADLE_PROJECT_db_password: dbpassword

    - name: Publish to GitHub Packages
      run: ./gradlew :persistence-module:publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}